### ISSUE TITLE
mysql 5.7 not working anymore

### ISSUE THREAD

**Issue by earonesty** [ankane/setup-mysql#5]
thinking maybe needs to be mariadb now?

https://github.com/AtakamaLLC/notanorm/actions/runs/3422534560/jobs/5700058602

**Comment by ankane** [comment]
Hey @earonesty, this action doesn't support 5.7 on `ubuntu-20.04`. https://github.com/ankane/setup-mysql#versions

**Comment by ankane** [comment]
Improved the error message in the commit above.

**Comment by earonesty** [comment]
oops, thanks!
