### ISSUE TITLE
windows 2022, mysql 5.7

### ISSUE THREAD

**Issue by earonesty** [ankane/setup-mysql#6]
issue with windows 2022, mysql 5.7

https://github.com/AtakamaLLC/notanorm/actions/runs/4690819077/jobs/8314442573

```
MySQLdb.OperationalError: (1045, "Access denied for user 'runneradmin'@'localhost' (using password: NO)")
```

"runneradmin" user not set up with access

**Comment by earonesty** [comment]
i suspect it's being set up for "root" not runneradmin?

**Comment by ankane** [comment]
Hey @earonesty, sorry for the long delay. The default user on Windows is `ODBC` (which is what `mysql` uses if no user is specified), but you can also use `root`.

```sh
mysql -e 'SELECT CURRENT_USER()' # returns ODBC@localhost
```
